use pokemon;
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Bulbasaur", "Grass", "001", "Vine Whip", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Ivysaur", "Grass", "002", "Mega Drain", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Venusaur", "Grass", "003", "Solar Beam", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Charmander", "Fire", "004", "Ember", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Charmeleon", "Fire", "005", "Flame Thrower", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Charizard", "Fire", "006", "Inferno", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Sqirtle", "Water", "007", "Water Pulse", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Wartortle", "Water", "008", "Water Gun", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Blastoise", "Water", "009", "Hydro Pump", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Caterpie", "Bug", "010", "Bug Bite", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Metapod", "Bug", "011", "Harden", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Butterfree", "Bug", "012", "Poison Powder", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Weedle", "Bug", "013", "Peck", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Kakuna", "Bug", "014", "Headbutt", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Beedrill", "Bug", "015", "Sting", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Pidgey", "Flying", "016", "Peck", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Pidgeotto", "Flying", "017", "Wing Attack", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Pidgeot", "Flying", "018", "Steel Wing", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Rattata", "Normal", "019", "Scratch", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Raticate", "Normal", "020", "Quick Attack", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Spearow", "Flying", "021", "Peck", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Fearow", "Flying", "022", "Ariel Ace", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Ekans", "Poison", "023", "Poison Sting", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Arbok", "Poison", "024", "Acid", "");
insert into pokecharacter (pokeName, energyType, cardId, attack, nickname) values ("Pikachu", "Electric", "025", "Thunderbolt", "");